name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: todo-app-v2
  DOCKER_REPOSITORY_ID: todo-app-repository-v2
  CLOUD_RUN_SERVICE_NAME: todo-cloud-run-service-v2
  GCP_REGION: europe-north1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authorize GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json:  ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker to Artifact Registry
      run: |
        gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_NAME }} .            

    - name: Tag and Push Docker image
      run: |
        docker tag ${{ env.DOCKER_IMAGE_NAME }} europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.DOCKER_REPOSITORY_ID }}/${{ env.DOCKER_IMAGE_NAME }}:latest
        docker push europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.DOCKER_REPOSITORY_ID }}/${{ env.DOCKER_IMAGE_NAME }}:latest

    - name: Deploy to Cloud Run
      id: deploy
      run: |
        gcloud run deploy ${{ env.CLOUD_RUN_SERVICE_NAME }} --image europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.DOCKER_REPOSITORY_ID }}/${{ env.DOCKER_IMAGE_NAME }}:latest \
        --region ${{ env.GCP_REGION }} --platform managed --allow-unauthenticated --quiet --format=json
        echo ::set-output name=url::$(gcloud run services describe ${{ env.CLOUD_RUN_SERVICE_NAME }} --region ${{ env.GCP_REGION }} --format='value(status.url)')